### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by carstenbauer**
* Update to Documenter v1.
* Adding a references page.
* Improve examples (e.g. mitigate false sharing etc.)
* Improve batch vs scatter plot
* Improve explanation (once more)

### CODE REVIEW

**Comment by carstenbauer** [comment]
If CI passes, this is ready to be merged IMHO. (cc @lmiq)

**Comment by lmiq** [comment]
Thank you very much!

One thing only: is there a compelling argument for using `map/do/fetch` instead of `@sync` and a simple loop? I find the use of `map` much harder to understand there, particularly in what the chunks and ranges mean in those examples.

**Comment by lmiq** [comment]
Thank you very much!

One thing only: is there a compelling argument for using `map/do/fetch` instead of `@sync` and a simple loop? I find the use of `map` much harder to understand there, particularly in what the chunks and ranges mean in those examples.

**Comment by carstenbauer** [comment]
> One thing only: is there a compelling argument for using `map/do/fetch` instead of `@sync` and a simple loop? I find the use of `map` much harder to understand there, particularly in what the chunks and ranges mean in those examples.

I'd argue that the `map` approach (1) cleanly highlights the data-parallel character, (2) discourages mutation (which is generally to be avoided in parallel algorithms), and, as a consequence of (2), naturally avoids potential race conditions. A simple loop unfortunately incentivises mutation (of a preallocated buffer) and, if done the wrong way (as is easily the case and also was the case before this PR), leads to issues like false sharing or - even worse - race conditions.

Note that the Julia docs themselves have a ["good" parallel sum implementation](https://docs.julialang.org/en/v1/manual/multi-threading/#Using-@threads-without-data-races) that is also written in terms of `map` and is virtually identical to what I present here.

(Having said all that, loops are still fine, of course, if you know what you're doing.)

**Comment by lmiq** [comment]
Retrospectively I think `chunks` should return only the index ranges, and to get the chunk number one should use `enumerate` . That would make the use of map cleaner.

**Pull request merged**
